---

- hosts: localhost
  roles:
    - packages
  tasks:

    - name: Install docker and compose
      include_role:
        name: bootstrap
        tasks_from: docker.yml

    # See https://github.com/aws/amazon-ecs-agent for all the shiny gubbins

    - name: Create our required directories
      file:
        state: present
        type: directory
        path: "{{ item }}"
      with_items:
        - /var/log/ecs
        - /etc/ecs
        - /var/lib/ecs/data
      become: true

    - name: Ensure our ECS config file exists
      copy:
        dest: /etc/ecs/ecs.config
        content: |
          ECS_DATADIR=/data
          ECS_ENABLE_TASK_IAM_ROLE=true
          ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
          ECS_LOGFILE=/log/ecs-agent.log
          ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
          ECS_LOGLEVEL=info
          ECS_CLUSTER=default
      become: true

    - name: Configure our sysctl entries
      sysctl:
        name: net.ipv4.conf.all.route_localnet
        value: 1
        state: present

    - name: Configure our iptables for ecs
      iptables:
        table: nat
        action: append
        chain: "{{ item.chain }}"
        protocol: "{{ item.protocol|default('tcp') }}"
        match: "{{ item.match|default([]) }}"
        destination: "169.254.170.2"
        destination_port: "80"
        jump: "{[ item.jump }}"
        to_destination: "{{ item.to_dest|default('') }}"
        to_ports: "{{ item.to_ports|default('') }}"
      with_items:
        - {chain: "PREROUTING", jump: "DNAT", to_dest: "127.0.0.1:51679"}
        - {chain: "OUTPUT", jump: "REDIRECT", match: "tcp", to_ports: "51679"}
      become: true

    - name: Get our ecs-agent
      docker_image:
        name: docker pull amazon/amazon-ecs-agent

    - name: Run our ecs container
      raw: "docker run --name ecs-agent \
            --detach=true \
            --restart=on-failure:10 \
            --volume=/var/run/docker.sock:/var/run/docker.sock \
            --volume=/var/log/ecs:/log \
            --volume=/var/lib/ecs/data:/data \
            --net=host \
            --env-file=/etc/ecs/ecs.config \
            --env=ECS_LOGFILE=/log/ecs-agent.log \
            --env=ECS_DATADIR=/data/ \
            --env=ECS_ENABLE_TASK_IAM_ROLE=true \
            --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
            amazon/amazon-ecs-agent:latest"
      become: true
