---

- hosts: localhost
  roles:
    - dev-sec.os-hardening
    - linuxhq.yum_cron
    - sys_user
  tasks:
    - name: Disable selinux permanently
      selinux:
        state: disabled
      become: true
