---

- hosts: localhost
  roles:
    - packages
  tasks:

    - name: Install docker and compose
      include_role:
        name: bootstrap
        tasks_from: docker.yml

    - name: Create our system user and add it to the docker group
      include_role:
        name: sys_user

    # See https://github.com/aws/amazon-ecs-agent for all the shiny gubbins
    - name: Create our required directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/var/log/ecs"
        - "/etc/ecs"
        - "/var/lib/ecs/data"
      become: true

    - name: Ensure our ECS config file exists
      copy:
        dest: /etc/ecs/ecs.config
        content: |
          ECS_DATADIR=/data
          ECS_ENABLE_TASK_IAM_ROLE=true
          ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
          ECS_LOGFILE=/log/ecs-agent.log
          ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
          ECS_LOGLEVEL=info
          ECS_CLUSTER=default
      become: true

    - name: Configure our sysctl entries
      sysctl:
        name: net.ipv4.conf.all.route_localnet
        value: 1
        state: present

    - name: Configure our iptables for ecs
      iptables:
        table: nat
        action: append
        chain: "PREROUTING"
        protocol: "tcp"
        destination: "169.254.170.2"
        destination_port: "80"
        jump: "DNAT"
        to_destination: "127.0.0.1:51679"
      become: true

    - name: Configure our iptables for ecs
      iptables:
        table: nat
        action: append
        chain: "OUTPUT"
        protocol: "tcp"
        match: "tcp"
        destination: "169.254.170.2"
        destination_port: "80"
        jump: "REDIRECT"
        to_ports: "51679"
      become: true

    - name: Get our ecs-agent
      docker_image:
        name: amazon/amazon-ecs-agent

    - name: Run our ecs container
      raw: "docker run --name ecs-agent \
            --detach=true \
            --restart=on-failure:10 \
            --volume=/var/run/docker.sock:/var/run/docker.sock \
            --volume=/var/log/ecs:/log \
            --volume=/var/lib/ecs/data:/data \
            --net=host \
            --env-file=/etc/ecs/ecs.config \
            --env=ECS_LOGFILE=/log/ecs-agent.log \
            --env=ECS_DATADIR=/data/ \
            --env=ECS_ENABLE_TASK_IAM_ROLE=true \
            --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
            amazon/amazon-ecs-agent:latest"
      become: true
