---

- hosts: localhost
  roles:
    - dev-sec.os-hardening
    - linuxhq.yum_cron
    - sys_user
  tasks:
    - name: Ensure we don't have reference to ptrace in our sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "kernel.yama.ptrace_scope="
        state: absent
      become: true

    - name: Disable selinux permanently
      selinux:
        state: disabled
      become: true

    - name: Import the elrepo GPG key
      command: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
      become: true
      args:
        warn: false

    - name: Import the elrepo repository
      command: rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
      become: true
      args:
        warn: false

# Currently we only need this for alfresco clustering on aws which is yet to be implemented
# and the new kernel is having knock on implications with oracle products
# So we are removing this for now until we get time to fully test the implications of
# upgrading our kernel

#
#    - name: Install our new kernel
#      yum:
#        name: kernel-ml
#        state: present
#        enablerepo: elrepo-kernel
#      become: true
#
#    - name: Set our new kernel as default
#      command: grub2-set-default 0
#      become: true
#
#    - name: Regenerate grub
#      command: grub2-mkconfig -o /boot/grub2/grub.cfg
#      become: true
#
#    - name: Clean up old kernels
#      command: package-cleanup --oldkernels
#      become: true
