---

- hosts: localhost
  roles:
    - packages
  tasks:

    - name: Ensure our configure_github script is executeable
      file:
        dest:  /home/centos/configure_github
        mode: a+x
      become: true

    - name: Install Maven
      yum:
        name: apache-maven
        state: present

    - name: Install Goss
      raw: "curl -fsSL https://goss.rocks/install | sh"
      become: true
