---

- hosts: localhost
  roles:
    - os-hardening
    - linuxhq.yum_cron
    - sys_user
    - packages
  tasks:
    - name: Disable selinux permanently
      selinux:
        state: disabled
      become: true

    - name: Ensure we don't have reference to ptrace in our sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "kernel.yama.ptrace_scope="
        state: absent
      become: true

    - name: Copy AWS ebsnvme-id script
      copy:
        src: /tmp/ebsnvme-id
        dest: /usr/sbin/ebsnvme-id
        owner: root
        group: root
        mode: 0755

    - name: Copy udev rules for nvme disks
      copy:
        src: /tmp/90-ec2-nvme-devices.rules
        dest: /etc/udev/rules.d/90-ec2-nvme-devices.rules
        owner: root
        group: root
        mode: 0544
