- src: dev-sec.os-hardening
- src: linuxhq.yum_cron
- name: sys_user
  src:  https://github.com/ministryofjustice/hmpps-delius-core-system-user.git
- name: packages
  src:  https://github.com/ministryofjustice/hmpps-ansible-packages.git
