---

- hosts: localhost
  tasks:
    - name: create local group to contain new users
      win_group:
        name: Jenkins
        description: Allow access to C:\Jenkins folder

    - name: Create our windows slave user
      win_user:
        name: jenkins-slave
        password: "{{ jenkins_slave_password }}"
        state: present
        groups:
          - User
          - Service
          - Jenkins

    - name: Create Jenkins Folder
      win_file:
        path: C:\Jenkins
        state: directory

    - name: set ACL of Jenkins folder
      win_acl:
        path: C:\Jenkins
        rights: FullControl
        state: present
        type: allow
        user: Jenkins

    - name: remove parent inheritance of Jenkins folder
      win_acl_inheritance:
        path: C:\Jenkins
        reorganize: yes
        state: absent
